[project]
org-name="laf"
version="0.1.0"

[dependencies]
"wso2/twitter"="0.9.26"
"laf/zip"="0.1.3"

[platform]
target = "java8"

[[platform.libraries]]
path = "/home/laf/mysql-connector-java-8.0.18.jar"
modules = ["calfunctions"]

[[platform.libraries]]
path = "/home/laf/mssql-jdbc-7.4.1.jre8.jar"
modules = ["calfunctions"]
